all:
	g++ -c Wrapper.cpp -c ResultSet.cpp -c Wrapper.cpp -c Query.cpp -c QueryHelper.cpp -c ResultSet.cpp -c MySqlException.h -c Transaction.h -I/usr/local/mysql/include -L/usr/local/mysql/lib -lmysqlclient_r 


clean:
	rm -rf Wrapper
